databases:
  - name: bible-books
    databaseName: bible-books
    user: bible-books

services:
  - type: web
    name: bible-books
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bible-books
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false