databases:
  - name: biblebooks
    databaseName: biblebooks
    user: biblebooks

services:
  - type: web
    name: biblebooks
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: biblebooks
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false